<?php

namespace App\Services;

use App\DTOs\ProductDTO;

class MakeupService
{
    /**
     * @return array<ProductDTO>
     */
    public function getAllProducts(): array
    {
        $img = 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=600';
        $imgBase = 'https://images.unsplash.com/photo-1512496115841-a45b7367c3bb?auto=format&fit=crop&q=80&w=600';
        $imgLip = 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=600';

        return [
            // Maquillajes
            new ProductDTO(
                id: 1,
                name: 'Base Maybelline Fit me 12H Matte + Poreless',
                category: 'Maquillajes',
                price: 'C$ 430.00',
                image: $imgBase,
                description: 'Base de maquillaje líquida de acabado mate natural y control de brillo hasta por 12 horas; minimiza poros y se adapta al tono y textura de la piel.',
                brand: 'Maybelline',
                priceNumeric: 430,
            ),
            new ProductDTO(
                id: 2,
                name: 'Polvo compacto Maybelline Fit me',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Polvo compacto matificante de larga duración que sella el maquillaje, controla el exceso de grasa y deja un acabado suave y sin brillo.',
                brand: 'Maybelline',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 3,
                name: 'L\'Oréal Infallible Pro-Matte',
                category: 'Maquillajes',
                price: 'C$ 430.00',
                image: $imgBase,
                description: 'Base de alta cobertura con acabado mate aterciopelado hasta por 24 horas; fórmula ligera y libre de aceites que resiste el sudor y la humedad.',
                brand: 'L\'Oréal',
                priceNumeric: 430,
            ),
            new ProductDTO(
                id: 4,
                name: 'Corrector e.l.f. Hydrating Camo',
                category: 'Maquillajes',
                price: 'C$ 450.00',
                image: $img,
                description: 'Corrector líquido de cobertura completa con acabado satinado e hidratante; enriquecido con hialuronato de sodio y rosa damascena.',
                brand: 'e.l.f.',
                priceNumeric: 450,
            ),
            new ProductDTO(
                id: 5,
                name: 'NYX Pore Filler Primer',
                category: 'Maquillajes',
                price: 'C$ 350.00',
                image: $img,
                description: 'Prebase facial perfeccionadora con textura sedosa que difumina poros, líneas de expresión e imperfecciones para un lienzo liso antes del maquillaje.',
                brand: 'NYX',
                priceNumeric: 350,
            ),
            new ProductDTO(
                id: 6,
                name: 'Primer E.l.f',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Primer facial preparador que alisa la textura de la piel, prolonga la duración del maquillaje y deja una base impecable y uniforme.',
                brand: 'e.l.f.',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 7,
                name: 'Tinta de Labios e.l.f.',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $imgLip,
                description: 'Tinta labial ligera y de larga duración que aporta un velo de color natural y fresco con acabado jugoso y sensación no pegajosa.',
                brand: 'e.l.f.',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 8,
                name: 'Maybelline Super Stay Ink Crayon',
                category: 'Maquillajes',
                price: 'C$ 350.00',
                image: $imgLip,
                description: 'Labial en crayón mate de hasta 8 horas de duración con afilador incorporado; ofrece precisión milimétrica y color intenso de una sola pasada.',
                brand: 'Maybelline',
                priceNumeric: 350,
            ),
            new ProductDTO(
                id: 9,
                name: 'Gloss e.l.f',
                category: 'Maquillajes',
                price: 'C$ 450.00',
                image: $imgLip,
                description: 'Brillo labial voluminizador de alto brillo enriquecido con aceites nutritivos y vitamina E para unos labios suaves, rellenos y resplandecientes.',
                brand: 'e.l.f.',
                priceNumeric: 450,
            ),
            new ProductDTO(
                id: 10,
                name: 'Labiales Maybelline Super Stay Matte Ink',
                category: 'Maquillajes',
                price: 'C$ 420.00',
                image: $imgLip,
                description: 'Labial líquido mate intransferible de fijación extrema hasta por 16 horas; fórmula con pigmentos ultraconcentrados y aplicador en flecha.',
                brand: 'Maybelline',
                priceNumeric: 420,
            ),
            new ProductDTO(
                id: 11,
                name: 'Gloss Maybelline',
                category: 'Maquillajes',
                price: 'C$ 420.00',
                image: $imgLip,
                description: 'Brillo labial hidratante con ácido hialurónico (Lifter Gloss); hidrata profundamente y aporta un acabado brillante con efecto lifting visible.',
                brand: 'Maybelline',
                priceNumeric: 420,
            ),
            new ProductDTO(
                id: 12,
                name: 'Rubor NYX',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $img,
                description: 'Rubor en polvo sedoso de alta pigmentación y fácil difuminado; brinda a las mejillas un rubor saludable, radiante y duradero.',
                brand: 'NYX',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 13,
                name: 'Labiales L\'Oréal Paris Mate',
                category: 'Maquillajes',
                price: 'C$ 420.00',
                image: $imgLip,
                description: 'Labial mate cremoso enriquecido con aceites puros y pigmentos intensos; brinda confort extremo sin resecar y color duradero de impacto.',
                brand: 'L\'Oréal',
                priceNumeric: 420,
            ),
            new ProductDTO(
                id: 14,
                name: 'Rubor líquido e.l.f.',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Rubor líquido ultra pigmentado con aplicador acolchado; se funde perfectamente en las mejillas aportando un toque de color luminoso y construible.',
                brand: 'e.l.f.',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 15,
                name: 'Primer NYX en spray',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $img,
                description: 'Spray preparador y fijador ligero que refresca la piel, sella el maquillaje y garantiza un acabado fresco y duradero todo el día.',
                brand: 'NYX',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 16,
                name: 'Bases e.l.f',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $imgBase,
                description: 'Base líquida perfeccionadora de textura ligera que unifica el tono facial y disimula imperfecciones dejando un acabado natural y luminoso.',
                brand: 'e.l.f.',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 17,
                name: 'Fijador de maquillaje L\'Oréal',
                category: 'Maquillajes',
                price: 'C$ 600.00',
                image: $img,
                description: 'Spray fijador Infallible de bruma ultrafina; fija el maquillaje hasta por 24 horas protegiéndolo contra el sudor, la humedad y el brillo.',
                brand: 'L\'Oréal',
                priceNumeric: 600,
            ),
            new ProductDTO(
                id: 18,
                name: 'Got2b Glued Styling Spiking Glue',
                category: 'Maquillajes',
                price: 'C$ 370.00',
                image: $img,
                description: 'Gel de fijación extrema a prueba de agua, ideal para fijar y laminar cejas de forma impecable durante todo el día sin dejar residuos blancos.',
                brand: 'Got2b',
                priceNumeric: 370,
            ),
            new ProductDTO(
                id: 19,
                name: 'Fijadores e.l.f',
                category: 'Maquillajes',
                price: 'C$ 450.00',
                image: $img,
                description: 'Bruma fijadora de maquillaje enriquecida con té verde, pepino y vitaminas A, C y E para hidratar la piel y mantener el look intacto por horas.',
                brand: 'e.l.f.',
                priceNumeric: 450,
            ),
            new ProductDTO(
                id: 20,
                name: 'Bronceador y contorno (e.l.f. Camo Liquid Bronzer)',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Bronceador líquido de fórmula cremosa e hidratante con aplicador esponja; esculpe, define y aporta un brillo cálido natural a los contornos.',
                brand: 'e.l.f.',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 21,
                name: 'Corrector de ojos Maybelline',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $img,
                description: 'Corrector iluminador y cubritivo para el área de los ojos; disimula ojeras, manchas y signos de fatiga dejando una mirada fresca y descansada.',
                brand: 'Maybelline',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 22,
                name: 'Polvo suelto fijador Infallible Blur-fection de L\'Oréal',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $img,
                description: 'Polvo traslúcido fijador con efecto difuminador de poros e imperfecciones; controla el brillo sin resecar y deja un acabado aterciopelado.',
                brand: 'L\'Oréal',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 23,
                name: 'Aceite Labial Voluminizador Hyaluronic de L\'Oréal',
                category: 'Maquillajes',
                price: 'C$ 420.00',
                image: $imgLip,
                description: 'Aceite labial enriquecido con ácido hialurónico y aceites florales; aporta brillo extremo, hidratación intensa y efecto de volumen instantáneo.',
                brand: 'L\'Oréal',
                priceNumeric: 420,
            ),
            new ProductDTO(
                id: 24,
                name: 'Halo Glow Liquid Filter',
                category: 'Maquillajes',
                price: 'C$ 440.00',
                image: $imgBase,
                description: 'Filtro líquido perfeccionador con escualano y ácido hialurónico; brinda a la piel un brillo radiante y efecto filtro de enfoque suave.',
                brand: 'e.l.f.',
                priceNumeric: 440,
            ),
            new ProductDTO(
                id: 25,
                name: 'Pixi by Petra On-the-Glow Blush (19gr)',
                category: 'Maquillajes',
                price: 'C$ 480.00',
                image: $img,
                description: 'Rubor en barra formulado con extracto de ginseng, aloe vera y ácidos de frutas; acondiciona e hidrata las mejillas con un toque natural de color.',
                brand: 'Pixi',
                priceNumeric: 480,
            ),
            new ProductDTO(
                id: 26,
                name: 'Polvo iluminador Pixi Glow-y Powder',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Polvo iluminador mineral micronizado con pigmentos reflectantes de luz; realza pómulos y puntos altos del rostro con un resplandor etéreo.',
                brand: 'Pixi',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 27,
                name: 'Tintas de labios Maybelline SuperStay Teddy Tint',
                category: 'Maquillajes',
                price: 'C$ 420.00',
                image: $imgLip,
                description: 'Tinta labial aterciopelada de textura ligera como peluche; ofrece color mate difuminado de larga duración que se siente ultrasuave en los labios.',
                brand: 'Maybelline',
                priceNumeric: 420,
            ),
            new ProductDTO(
                id: 28,
                name: 'L\'Oréal Paris Infallible 32 Hour Fresh Wear Foundation',
                category: 'Maquillajes',
                price: 'C$ 480.00',
                image: $imgBase,
                description: 'Base de maquillaje líquida ultratranspirable de hasta 32 horas de duración con vitamina C y SPF 25; resiste agua, sudor y transferencias.',
                brand: 'L\'Oréal',
                priceNumeric: 480,
            ),
            new ProductDTO(
                id: 29,
                name: 'Polvo Infallible 24H Fresh Wear de L\'Oréal',
                category: 'Maquillajes',
                price: 'C$ 420.00',
                image: $img,
                description: 'Base en polvo de cobertura total y acabado mate natural hasta por 24 horas; resistente al agua, calor y humedad sin cuartearse.',
                brand: 'L\'Oréal',
                priceNumeric: 420,
            ),
            new ProductDTO(
                id: 30,
                name: 'Base Maybelline Lumi Matte',
                category: 'Maquillajes',
                price: 'C$ 480.00',
                image: $imgBase,
                description: 'Base líquida de sensación ligera como el aire con acabado mate luminoso; ofrece cobertura modulable de larga duración y resistencia a la transferencia.',
                brand: 'Maybelline',
                priceNumeric: 480,
            ),
            new ProductDTO(
                id: 31,
                name: 'Corrector Skin Ink L\'Oréal',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $img,
                description: 'Corrector líquido de alta fijación y textura ultrafina; cubre imperfecciones y ojeras al instante con sensación imperceptible durante horas.',
                brand: 'L\'Oréal',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 32,
                name: 'Blush On the Glow Pixi (10gr)',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Presentación compacta de 10gr del icónico rubor en barra hidratante con aloe vera; ideal para retocar mejillas y labios en cualquier lugar.',
                brand: 'Pixi',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 33,
                name: 'Máscara de pestañas Great Lash de Maybelline',
                category: 'Maquillajes',
                price: 'C$ 420.00',
                image: $img,
                description: 'La máscara de pestañas clásica favorita que duplica el volumen; su cepillo constructor acondiciona y define pestaña a pestaña sin grumos.',
                brand: 'Maybelline',
                priceNumeric: 420,
            ),
            new ProductDTO(
                id: 34,
                name: 'Maybelline Great Lash Waterproof',
                category: 'Maquillajes',
                price: 'C$ 480.00',
                image: $img,
                description: 'Versión a prueba de agua de la icónica Great Lash; resiste lágrimas, humedad y frotamientos manteniendo un volumen definido todo el día.',
                brand: 'Maybelline',
                priceNumeric: 480,
            ),
            new ProductDTO(
                id: 35,
                name: 'Contour Halo Glow Elf',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Contorno líquido con aplicador de almohadilla suave; esculpe pómulos y mandíbula con facilidad integrándose a la perfección con la piel.',
                brand: 'e.l.f.',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 36,
                name: 'Gloss Serum NYX',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $imgLip,
                description: 'Brillo labial infusionado con suero nutritivo de electrolitos; nutre intensamente mientras aporta un acabado jugoso, radiante y sin sensación pegajosa.',
                brand: 'NYX',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 37,
                name: 'Pro Gloss L\'Oréal',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $imgLip,
                description: 'Brillo labial de alto impacto con aplicador ergonómico; viste los labios de un brillo espejo deslumbrante con confort absoluto.',
                brand: 'L\'Oréal',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 38,
                name: 'Blush Halo Glow Elf',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Rubor líquido iluminador Halo Glow Beauty Wand; se difumina sin esfuerzo aportando un rubor radiante y fresco con microdestellos luminosos.',
                brand: 'e.l.f.',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 39,
                name: 'Blush Stick Neutrogena',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $img,
                description: 'Barra multiusos para mejillas y labios con ácido hialurónico; añade un toque de color natural hidratante y saludable de aplicación rápida.',
                brand: 'Neutrogena',
                priceNumeric: 400,
            ),
            new ProductDTO(
                id: 40,
                name: 'Eraser Treatment Base Concealer',
                category: 'Maquillajes',
                price: 'C$ 450.00',
                image: $img,
                description: 'Corrector multifuncional Instant Age Rewind con aplicador esponja microcorrectora; borra ojeras, corrige líneas y redefine el rostro al instante.',
                brand: 'Maybelline',
                priceNumeric: 450,
            ),
            new ProductDTO(
                id: 41,
                name: 'Base Plump y Glow Maybelline',
                category: 'Maquillajes',
                price: 'C$ 450.00',
                image: $imgBase,
                description: 'Base fluida efecto rellenador y luminosidad saludable; hidrata profundamente y deja la piel radiante, elástica y rejuvenecida.',
                brand: 'Maybelline',
                priceNumeric: 450,
            ),
            new ProductDTO(
                id: 42,
                name: 'Polvo Finishing Powder C...',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Polvo fijador y de acabado mineral ultraligero; sella la base de maquillaje, matifica zonas con brillo y suaviza visualmente la textura facial.',
                brand: 'NYX',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 43,
                name: 'Corrector Maybelline',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Corrector de textura cremosa; camufla rojeces, granitos y manchas para un acabado natural sin marcar líneas de expresión.',
                brand: 'Maybelline',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 44,
                name: 'Corrector L\'Oréal',
                category: 'Maquillajes',
                price: 'C$ 400.00',
                image: $img,
                description: 'Corrector de máxima cobertura y fijación prolongada; disimula imperfecciones severas y ojeras oscuras con un acabado mate aterciopelado.',
                brand: 'L\'Oréal',
                priceNumeric: 400,
            ),

            // Productos Pixi
            new ProductDTO(
                id: 801,
                name: 'Pixi by Petra On-the-Glow Blush',
                category: 'Maquillajes',
                price: 'C$ 480.00',
                image: $img,
                description: 'Barra de rubor hidratante formulada con extracto de ginseng y aloe vera; acondiciona e hidrata la piel mientras otorga un rubor natural y saludable.',
                brand: 'Pixi',
                priceNumeric: 480,
            ),
            new ProductDTO(
                id: 802,
                name: 'Polvo Iluminador Pixi Glow-y Powder',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Polvo iluminador sedoso enriquecido con pigmentos perlados reflectores de luz; esculpe y resalta tus facciones con un brillo radiante de alta costura.',
                brand: 'Pixi',
                priceNumeric: 380,
            ),
            new ProductDTO(
                id: 803,
                name: 'Blush On the Glow Pixi (10gr)',
                category: 'Maquillajes',
                price: 'C$ 380.00',
                image: $img,
                description: 'Formato de viaje de 10gr del rubor sólido hidratante enriquecido con antioxidantes; ideal para dar color y luminosidad a mejillas y labios sobre la marcha.',
                brand: 'Pixi',
                priceNumeric: 380,
            ),
        ];
    }
}
