<?php

namespace App\Services;

use App\DTOs\ProductDTO;

class SkincareService
{
    /**
     * @return array<ProductDTO>
     */
    public function getAllProducts(): array
    {
        $img = 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=600'; // General skincare image

        return [
            // Skincare Coreano
            new ProductDTO(
                id: 201,
                name: 'Sérum Facial con Ácido Azelaico 12% TIRTIR',
                category: 'Skincare',
                price: 'C$ 1,100.00',
                image: $img,
                description: 'Suero calmante y unificador con 12% de ácido azelaico, ideal para desvanecer manchas, reducir rojeces y controlar brotes de acné.',
                brand: 'TIRTIR',
                skinType: 'Mixta',
                priceNumeric: 1100,
            ),
            new ProductDTO(
                id: 202,
                name: 'Ampolla Facial Madagascar Centella Asiatica 100ML Ampoule',
                category: 'Skincare',
                price: 'C$ 950.00',
                image: $img,
                description: 'Ampolla calmante con 100% extracto de Centella Asiática de Madagascar; repara la barrera cutánea, alivia irritaciones y aporta hidratación profunda.',
                brand: 'Skin1004',
                skinType: 'Sensible',
                priceNumeric: 950,
            ),
            new ProductDTO(
                id: 203,
                name: 'Crema Hidratante 147 Barrier Cream',
                category: 'Skincare',
                price: 'C$ 1,140.00',
                image: $img,
                description: 'Crema nutritiva e intensiva formulada para restaurar y proteger la barrera cutánea debilitada, reteniendo la humedad por horas.',
                brand: 'Skin1004',
                skinType: 'Seca',
                priceNumeric: 1140,
            ),
            new ProductDTO(
                id: 204,
                name: 'Ampolla Facial Iluminadora Tone Brightening Capsule Ampoule Jumbo',
                category: 'Skincare',
                price: 'C$ 940.00',
                image: $img,
                description: 'Ampolla iluminadora con microcápsulas de Madecassoside y Niacinamida que emparejan el tono de la piel y aportan luminosidad natural.',
                brand: 'Skin1004',
                skinType: 'Mixta',
                priceNumeric: 940,
            ),
            new ProductDTO(
                id: 205,
                name: 'Pure Glow Essentials Set',
                category: 'Skincare',
                price: 'C$ 1,100.00',
                image: $img,
                description: 'Set de esenciales para una rutina completa iluminadora e hidratante, diseñado para devolver vitalidad, suavidad y brillo al rostro.',
                brand: 'Skin1004',
                skinType: 'Mixta',
                priceNumeric: 1100,
            ),
            new ProductDTO(
                id: 206,
                name: 'Pine Calming Cica Trial Kit - Round Lab',
                category: 'Skincare',
                price: 'C$ 1,150.00',
                image: $img,
                description: 'Kit de viaje calmante a base de extracto de pino y cica; purifica suavemente los poros y calma pieles irritadas o con tendencia al enrojecimiento.',
                brand: 'Round Lab',
                skinType: 'Sensible',
                priceNumeric: 1150,
            ),
            new ProductDTO(
                id: 207,
                name: 'Mascarilla de Arcilla Madagascar Centella Poremizing Quick Clay Stick Mask',
                category: 'Skincare',
                price: 'C$ 700.00',
                image: $img,
                description: 'Mascarilla en barra de arcilla purificante y sal rosa del Himalaya; limpia profundamente los poros y absorbe el exceso de sebo sin resecar.',
                brand: 'Skin1004',
                skinType: 'Grasa',
                priceNumeric: 700,
            ),
            new ProductDTO(
                id: 208,
                name: 'Crema Hidratante Madagascar Centella Soothing Cream Bundle',
                category: 'Skincare',
                price: 'C$ 880.00',
                image: $img,
                description: 'Gel-crema refrescante enriquecido con Centella Asiática y ceramidas; calma al instante y refuerza la barrera de hidratación.',
                brand: 'Skin1004',
                skinType: 'Sensible',
                priceNumeric: 880,
            ),
            new ProductDTO(
                id: 209,
                name: 'Ampolla Facial Madagascar Centella Polemerizin 100ML',
                category: 'Skincare',
                price: 'C$ 900.00',
                image: $img,
                description: 'Ampolla minimizadora de poros con sal rosa del Himalaya y péptidos; mejora la elasticidad de los poros y controla la producción de grasa.',
                brand: 'Skin1004',
                skinType: 'Grasa',
                priceNumeric: 900,
            ),
            new ProductDTO(
                id: 210,
                name: 'Ampolla Facial Madagascar Centella Tea-Trica Relief Jumbo Ampoule',
                category: 'Skincare',
                price: 'C$ 1,050.00',
                image: $img,
                description: 'Ampolla SOS para pieles propensas al acné formulada con complejo Tea-Trica (árbol de té y cica) para calmar inflamaciones y brotes activos.',
                brand: 'Skin1004',
                skinType: 'Grasa',
                priceNumeric: 1050,
            ),
            new ProductDTO(
                id: 211,
                name: 'Madagascar Centella Hyalu-Cica Blue Serum 50 ML',
                category: 'Skincare',
                price: 'C$ 800.00',
                image: $img,
                description: 'Sérum ultraligero con fórmula Hyalu-Cica (Ácido Hialurónico + Centella Asiática) que brinda hidratación refrescante y calma duradera.',
                brand: 'Skin1004',
                skinType: 'Mixta',
                priceNumeric: 800,
            ),
            new ProductDTO(
                id: 212,
                name: 'Protector Solar en Barra Madagascar Centella Hyalu-Cica Silky-Fit Sun Stick',
                category: 'Skincare',
                price: 'C$ 650.00',
                image: $img,
                description: 'Protector solar en barra SPF50+ PA++++ de acabado sedoso y mate; hidrata con Hyalu-Cica y permite una reaplicación fácil sin sensación grasosa.',
                brand: 'Skin1004',
                skinType: 'Mixta',
                priceNumeric: 650,
            ),
            new ProductDTO(
                id: 213,
                name: 'Madagascar Centella Hyalu-Cica Travel Kit',
                category: 'Skincare',
                price: 'C$ 1,250.00',
                image: $img,
                description: 'Kit completo en formato de viaje con la línea Hyalu-Cica; ideal para mantener una piel profundamente hidratada y protegida en cualquier lugar.',
                brand: 'Skin1004',
                skinType: 'Mixta',
                priceNumeric: 1250,
            ),

            // Skincare e.l.f.
            new ProductDTO(
                id: 301,
                name: 'Makeup Melting Cleansing Balm XXL 100gr',
                category: 'Skincare',
                price: 'C$ 550.00',
                image: $img,
                description: 'Bálsamo limpiador desmaquillante en formato XXL con ácido hialurónico, ceramidas y péptidos; disuelve el maquillaje y las impurezas sin resecar.',
                brand: 'e.l.f.',
                skinType: 'Mixta',
                priceNumeric: 550,
            ),
            new ProductDTO(
                id: 302,
                name: 'Daily Cleanser (Holy Hydration!)',
                category: 'Skincare',
                price: 'C$ 480.00',
                image: $img,
                description: 'Limpiador facial diario en gel espumoso que elimina suciedad y maquillaje mientras retiene la humedad natural con ácido hialurónico y ceramidas.',
                brand: 'e.l.f.',
                skinType: 'Seca',
                priceNumeric: 480,
            ),
            new ProductDTO(
                id: 303,
                name: 'SKIN Bronzing Drops',
                category: 'Skincare',
                price: 'C$ 450.00',
                image: $img,
                description: 'Gotas bronceadoras iluminadoras con vitamina E y aceite de girasol; aportan un brillo cálido natural y besado por el sol al instante.',
                brand: 'e.l.f.',
                skinType: 'Mixta',
                priceNumeric: 450,
            ),
            new ProductDTO(
                id: 304,
                name: 'Holy Hydration! Sleeping Mask',
                category: 'Skincare',
                price: 'C$ 470.00',
                image: $img,
                description: 'Mascarilla nocturna ultra humectante con ácido hialurónico y ceramidas; nutre intensamente la piel mientras duermes para despertar con un rostro radiante.',
                brand: 'e.l.f.',
                skinType: 'Seca',
                priceNumeric: 470,
            ),
            new ProductDTO(
                id: 305,
                name: 'Eye Cream (Holy Hydration!)',
                category: 'Skincare',
                price: 'C$ 470.00',
                image: $img,
                description: 'Crema para el contorno de ojos enriquecida con péptidos y ácido hialurónico; hidrata a profundidad y minimiza la apariencia de ojeras.',
                brand: 'e.l.f.',
                skinType: 'Sensible',
                priceNumeric: 470,
            ),
            new ProductDTO(
                id: 306,
                name: 'Crema Facial / Holy Hydration! Face Cream',
                category: 'Skincare',
                price: 'C$ 450.00',
                image: $img,
                description: 'Crema hidratante ligera pero intensamente nutritiva con niacinamida, escualano y péptidos; deja la piel suave, tersa y luminosa.',
                brand: 'e.l.f.',
                skinType: 'Seca',
                priceNumeric: 450,
            ),
            new ProductDTO(
                id: 307,
                name: 'Thirst Burst Drops (Holy Hydration!)',
                category: 'Skincare',
                price: 'C$ 460.00',
                image: $img,
                description: 'Gotas concentradas de hidratación profunda formuladas con ácido hialurónico e ingredientes botánicos para revitalizar pieles deshidratadas.',
                brand: 'e.l.f.',
                skinType: 'Mixta',
                priceNumeric: 460,
            ),
            new ProductDTO(
                id: 308,
                name: 'Triple Bounce Serum (Holy Hydration!)',
                category: 'Skincare',
                price: 'C$ 500.00',
                image: $img,
                description: 'Sérum rellenador con complejo de ácido hialurónico al 1.75% y niacinamida; rellena visiblemente la piel y aporta máxima elasticidad y frescura.',
                brand: 'e.l.f.',
                skinType: 'Seca',
                priceNumeric: 500,
            ),
            new ProductDTO(
                id: 309,
                name: 'The Hottest Drops Duo',
                category: 'Skincare',
                price: 'C$ 400.00',
                image: $img,
                description: 'Dúo de gotas faciales perfeccionadoras que combinan hidratación y un toque de luminosidad bronceada para un acabado fresco y radiante.',
                brand: 'e.l.f.',
                skinType: 'Mixta',
                priceNumeric: 400,
            ),

            // Skincare CeraVe
            new ProductDTO(
                id: 401,
                name: 'Sérum Hidratante con Ácido Hialurónico 30ML',
                category: 'Skincare',
                price: 'C$ 700.00',
                image: $img,
                description: 'Gel-crema hidratante con alta concentración de ácido hialurónico, 3 ceramidas esenciales y vitamina B5 para restaurar la barrera protectora de la piel.',
                brand: 'CeraVe',
                skinType: 'Seca',
                priceNumeric: 700,
            ),
            new ProductDTO(
                id: 402,
                name: 'Loción Hidratante Facial CeraVe (AM con SPF 30) 60ML',
                category: 'Skincare',
                price: 'C$ 760.00',
                image: $img,
                description: 'Hidratante de día con protección solar SPF 30 de amplio espectro, enriquecido con ceramidas y niacinamida para calmar y proteger la piel.',
                brand: 'CeraVe',
                skinType: 'Mixta',
                priceNumeric: 760,
            ),
            new ProductDTO(
                id: 403,
                name: 'Eye Repair Cream (0.5oz)',
                category: 'Skincare',
                price: 'C$ 700.00',
                image: $img,
                description: 'Crema reparadora para el contorno de ojos con complejo botánico y marino, ceramidas y ácido hialurónico; reduce bolsas y ojeras visibles.',
                brand: 'CeraVe',
                skinType: 'Sensible',
                priceNumeric: 700,
            ),
            new ProductDTO(
                id: 404,
                name: 'Acne Clay-to-Foam Cleanser 118ML',
                category: 'Skincare',
                price: 'C$ 750.00',
                image: $img,
                description: 'Limpiador purificante de arcilla a espuma formulado para absorber el exceso de grasa, desobstruir poros y prevenir nuevos brotes sin irritar.',
                brand: 'CeraVe',
                skinType: 'Grasa',
                priceNumeric: 750,
            ),
            new ProductDTO(
                id: 405,
                name: 'Acne Control Gel (40ml)',
                category: 'Skincare',
                price: 'C$ 800.00',
                image: $img,
                description: 'Tratamiento diario para el acné con 2% de ácido salicílico (BHA), AHAs (glicólico y láctico) y ceramidas; elimina imperfecciones y minimiza poros.',
                brand: 'CeraVe',
                skinType: 'Grasa',
                priceNumeric: 800,
            ),
            new ProductDTO(
                id: 406,
                name: 'Sérum Retinol Resurfacing 30ML',
                category: 'Skincare',
                price: 'C$ 850.00',
                image: $img,
                description: 'Sérum con retinol encapsulado, extracto de raíz de regaliz y ceramidas; reduce marcas post-acné, minimiza poros y suaviza la textura de la piel.',
                brand: 'CeraVe',
                skinType: 'Sensible',
                priceNumeric: 850,
            ),

            // Skincare The Ordinary
            new ProductDTO(
                id: 501,
                name: 'The Acne Set',
                category: 'Skincare',
                price: 'C$ 1,100.00',
                image: $img,
                description: 'Set completo de 3 pasos (limpiador espumoso, ácido salicílico al 2% y factores naturales de hidratación) formulado para tratar y prevenir brotes de acné.',
                brand: 'The Ordinary',
                skinType: 'Grasa',
                priceNumeric: 1100,
            ),
            new ProductDTO(
                id: 502,
                name: 'Caffeine Solution 5% + EGCG 30ML',
                category: 'Skincare',
                price: 'C$ 600.00',
                image: $img,
                description: 'Suero concentrado de cafeína al 5% y EGCG de hojas de té verde; reduce notablemente la hinchazón, bolsas y ojeras oscuras en el contorno de ojos.',
                brand: 'The Ordinary',
                skinType: 'Mixta',
                priceNumeric: 600,
            ),
            new ProductDTO(
                id: 503,
                name: 'Niacinamide 10% + Zinc 1% 30ML',
                category: 'Skincare',
                price: 'C$ 550.00',
                image: $img,
                description: 'Fórmula potente con 10% de niacinamida y 1% de zinc PCA; regula la producción excesiva de sebo, descongestiona poros y minimiza imperfecciones.',
                brand: 'The Ordinary',
                skinType: 'Grasa',
                priceNumeric: 550,
            ),
            new ProductDTO(
                id: 504,
                name: 'Glycolic Acid 7% Exfoliating Toner 240ML',
                category: 'Skincare',
                price: 'C$ 1,000.00',
                image: $img,
                description: 'Tónico exfoliante con 7% de ácido glicólico (AHA), aloe vera y pimienta de Tasmania; afina la textura cutánea, desvanece manchas y aporta luminosidad.',
                brand: 'The Ordinary',
                skinType: 'Mixta',
                priceNumeric: 1000,
            ),
            new ProductDTO(
                id: 505,
                name: 'AHA 30% + BHA 2% Peeling Solution 30ML',
                category: 'Skincare',
                price: 'C$ 600.00',
                image: $img,
                description: 'Peeling facial exfoliante de 10 minutos con 30% AHAs y 2% BHA; exfolia profundamente los poros, combate imperfecciones y renueva la textura de la piel.',
                brand: 'The Ordinary',
                skinType: 'Mixta',
                priceNumeric: 600,
            ),
            new ProductDTO(
                id: 506,
                name: 'Soothing & Barrier Support Serum',
                category: 'Skincare',
                price: 'C$ 900.00',
                image: $img,
                description: 'Suero multiactivo con vitamina B12, ceramidas y centella asiática; repara la barrera cutánea debilitada, calma la irritación y disminuye rojeces.',
                brand: 'The Ordinary',
                skinType: 'Sensible',
                priceNumeric: 900,
            ),
            new ProductDTO(
                id: 507,
                name: 'Multi-Peptide Lash and Brow Serum',
                category: 'Skincare',
                price: 'C$ 850.00',
                image: $img,
                description: 'Suero concentrado con complejo de péptidos y extractos botánicos; nutre, fortalece y promueve el grosor y densidad de pestañas y cejas.',
                brand: 'The Ordinary',
                skinType: 'Mixta',
                priceNumeric: 850,
            ),
            new ProductDTO(
                id: 508,
                name: 'Hyaluronic Acid 2% + B5 (With Ceramides)',
                category: 'Skincare',
                price: 'C$ 650.00',
                image: $img,
                description: 'Suero hidratante de nueva generación con ácido hialurónico multimolecular, vitamina B5 y ceramidas; rellena e hidrata profundamente la piel.',
                brand: 'The Ordinary',
                skinType: 'Seca',
                priceNumeric: 650,
            ),
            new ProductDTO(
                id: 509,
                name: 'Retinol 1% in Squalane',
                category: 'Skincare',
                price: 'C$ 650.00',
                image: $img,
                description: 'Solución antiedad concentrada con 1% de retinol puro en base de escualano; suaviza líneas de expresión, combate el daño solar y mejora la textura.',
                brand: 'The Ordinary',
                skinType: 'Sensible',
                priceNumeric: 650,
            ),
            new ProductDTO(
                id: 510,
                name: 'Glycolic Acid 7% Exfoliating Toner 100ML',
                category: 'Skincare',
                price: 'C$ 600.00',
                image: $img,
                description: 'Presentación de 100ml de tónico exfoliante con ácido glicólico al 7%; limpia poros, unifica el tono facial y devuelve la luminosidad natural.',
                brand: 'The Ordinary',
                skinType: 'Mixta',
                priceNumeric: 600,
            ),

            // Haircare The Ordinary
            new ProductDTO(
                id: 601,
                name: 'Natural Moisturizing Factors + HA for Scalp',
                category: 'Skincare',
                price: 'C$ 800.00',
                image: $img,
                description: 'Tratamiento lechoso ultraligero para el cuero cabelludo que imita los factores naturales de hidratación para calmar la resequedad sin engrasar el cabello.',
                brand: 'The Ordinary',
                skinType: 'Sensible',
                priceNumeric: 800,
            ),

            // Filtros UV
            new ProductDTO(
                id: 701,
                name: 'Loción Hidratante Facial CeraVe (AM Facial Moisturising Lotion SPF 30) 60ML',
                category: 'Skincare',
                price: 'C$ 760.00',
                image: $img,
                description: 'Loción facial diaria con factor de protección solar SPF 30, 3 ceramidas esenciales y niacinamida; protege contra rayos UV e hidrata 24 horas.',
                brand: 'CeraVe',
                skinType: 'Mixta',
                priceNumeric: 760,
            ),
            new ProductDTO(
                id: 702,
                name: 'Suero con filtro UV SPF 45 (The Ordinary)',
                category: 'Skincare',
                price: 'C$ 1,200.00',
                image: $img,
                description: 'Protector solar facial en suero ultra fluido con SPF 45; aporta protección solar avanzada de amplio espectro sin dejar sensación pesada ni rastro blanco.',
                brand: 'The Ordinary',
                skinType: 'Sensible',
                priceNumeric: 1200,
            ),
        ];
    }
}
